import React, { useState, useEffect } from "react";
import API from "../services/api";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

const ReceiptsPage = () => {
  const [receipts, setReceipts]     = useState([]);
  const [loading, setLoading]       = useState(true);
  const [error, setError]           = useState(null);
  const [generating, setGenerating] = useState(null);
  const user = JSON.parse(localStorage.getItem("user")) || {};

  useEffect(() => {
    if (!user.username) return;
    API.get(`/fees/receipts/${user.username}`)
      .then((res) => setReceipts(res.data))
      .catch(() => setError("Failed to load receipts"))
      .finally(() => setLoading(false));
  }, [user.username]);

  const badgeClass = (s) =>
    s === "PAID" || s === "Received" ? "badge badge-green" : "badge badge-yellow";

  const handleDownload = async (r) => {
    setGenerating(r.receiptId);
    try {
      const doc  = await PDFDocument.create();
      const page = doc.addPage([595, 842]);
      const { width } = page.getSize();
      const margin = 50, rightX = width - margin, contentW = rightX - margin;

      const bold   = await doc.embedFont(StandardFonts.HelveticaBold);
      const normal = await doc.embedFont(StandardFonts.Helvetica);

      const indigo   = rgb(0.31, 0.275, 0.898);
      const white    = rgb(1, 1, 1);
      const slate8   = rgb(0.118, 0.161, 0.231);
      const slate5   = rgb(0.392, 0.455, 0.549);
      const slate4   = rgb(0.58, 0.639, 0.722);
      const green6   = rgb(0.086, 0.639, 0.29);
      const indigoBg = rgb(0.929, 0.914, 0.996);
      const greenBg  = rgb(0.941, 0.996, 0.957);
      const yellowBg = rgb(0.996, 0.976, 0.765);
      const yellowTx = rgb(0.522, 0.302, 0.055);
      const borderC  = rgb(0.886, 0.91, 0.941);

      const ln   = (x1,y1,x2,y2,color=borderC,t=0.5) => page.drawLine({ start:{x:x1,y:y1}, end:{x:x2,y:y2}, thickness:t, color });
      const rect = (x,y,w,h,color) => page.drawRectangle({ x, y, width:w, height:h, color });
      const txt  = (s,x,y,font,size,color) => page.drawText(s, { x, y, font, size, color });
      const rtxt = (s,rx,y,font,size,color) => { const tw = font.widthOfTextAtSize(s,size); txt(s, rx-tw, y, font, size, color); };

      rect(0, 752, width, 90, indigo);
      txt("COLLEGE FEE RECEIPT", margin, 804, bold, 20, white);
      txt("Student Portal  —  Official Payment Acknowledgement", margin, 782, normal, 10, rgb(0.8,0.8,1));

      rect(margin, 726, contentW, 24, indigoBg);
      txt("Receipt ID:", margin+8, 734, bold, 11, indigo);
      txt(r.receiptId, margin+90, 734, normal, 11, slate8);

      let y = 696;
      const section = (title) => { txt(title.toUpperCase(), margin, y, bold, 8, slate4); y-=8; ln(margin,y,rightX,y); y-=18; };
      const row     = (label, value) => { txt(label, margin, y, normal, 11, slate5); rtxt(value||"—", rightX, y, normal, 11, slate8); y-=18; };

      section("Payment Details");
      row("Date", r.date ?? "—");
      row("Payment Method", r.paymentMethod ?? "—");
      row("Status", r.status ?? "—");
      y -= 8;

      section("Amount");
      rect(margin, y-6, contentW, 28, greenBg);
      txt("Total Paid", margin+8, y+6, bold, 13, green6);
      rtxt("Rs. " + Number(r.amount).toLocaleString("en-IN", { minimumFractionDigits:2 }), rightX-8, y+6, bold, 13, green6);
      y -= 40;

      section("Student");
      row("Username", user.username ?? "—");
      row("Email",    user.email    ?? "—");
      y -= 8;

      rect(margin, y-14, contentW, 36, yellowBg);
      txt("This is a computer-generated receipt and does not require a physical signature.", margin+8, y+8, normal, 9, yellowTx);
      txt("Please retain this document for your records.", margin+8, y-4, normal, 9, yellowTx);

      rect(0, 0, width, 40, rgb(0.976, 0.98, 0.992));
      ln(0, 40, width, 40);
      txt("Generated by Student Portal", margin, 14, normal, 9, slate4);
      rtxt("Generated on: " + new Date().toLocaleString("en-IN"), rightX, 14, normal, 9, slate4);

      const pdfBytes = await doc.save();
      const blob = new Blob([pdfBytes], { type:"application/pdf" });
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement("a");
      a.href = url; a.download = `Receipt_${r.receiptId}.pdf`; a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("PDF error:", err);
      alert("PDF generation failed: " + err.message);
    } finally {
      setGenerating(null);
    }
  };

  const handlePrint = (r) => {
    const win = window.open("", "_blank");
    win.document.write(`
      <html><head><title>Receipt ${r.receiptId}</title>
      <style>body{font-family:Segoe UI,sans-serif;padding:40px;color:#1e293b;}h2{border-bottom:2px solid #4f46e5;padding-bottom:10px;color:#4f46e5;}.row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #f1f5f9;font-size:14px;}.lbl{color:#94a3b8;font-weight:600;}.total{font-size:18px;font-weight:700;margin-top:16px;padding-top:16px;border-top:2px solid #e2e8f0;}.footer{margin-top:40px;color:#94a3b8;font-size:12px;text-align:center;}</style>
      </head><body>
      <h2>College Fee Receipt</h2>
      <div class="row"><span class="lbl">Receipt ID</span><span>${r.receiptId}</span></div>
      <div class="row"><span class="lbl">Date</span><span>${r.date}</span></div>
      <div class="row"><span class="lbl">Payment Method</span><span>${r.paymentMethod}</span></div>
      <div class="row"><span class="lbl">Status</span><span>${r.status}</span></div>
      <div class="row total"><span>Total Amount</span><span>Rs. ${Number(r.amount).toLocaleString("en-IN",{minimumFractionDigits:2})}</span></div>
      <div class="footer">Generated from Student Portal — Thank you for your payment!</div>
      </body></html>
    `);
    win.document.close(); win.print();
  };

  if (loading) return (
    <div style={{ display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", height:"60vh", gap:"14px", color:"#64748b" }}>
      <div className="loading-spinner" />Loading...
    </div>
  );

  return (
    <>
      <h2 className="section-title">Receipts</h2>

      {error && (
        <div className="student-error">
          <i className="bx bxs-error" style={{ marginRight:"6px" }}></i>{error}
        </div>
      )}

      {receipts.length === 0 ? (
        <div className="table-wrapper"><p className="no-data">No receipts found.</p></div>
      ) : (
        <>
          <div className="stats-grid" style={{ gridTemplateColumns:"repeat(2,1fr)", maxWidth:"460px" }}>
            <div className="stat-card blue">
              <div className="stat-icon"><i className="bx bxs-file-pdf"></i></div>
              <div><p className="stat-label">Total Receipts</p><h3 className="stat-number">{receipts.length}</h3></div>
            </div>
            <div className="stat-card green">
              <div className="stat-icon"><i className="bx bxs-rupee"></i></div>
              <div><p className="stat-label">Total Amount</p><h3 className="stat-number">₹{receipts.reduce((s,r) => s+r.amount, 0).toLocaleString()}</h3></div>
            </div>
          </div>

          <div className="receipts-grid">
            {receipts.map((r, i) => (
              <div key={i} className="receipt-card">
                <div className="receipt-card-header">
                  <h4>Receipt #{r.receiptId}</h4>
                  <span className={badgeClass(r.status)}>{r.status}</span>
                </div>
                <div className="receipt-detail-row"><span>Date</span><span>{r.date}</span></div>
                <div className="receipt-detail-row">
                  <span>Amount</span>
                  <span style={{ fontWeight:700, color:"#1e293b" }}>₹{r.amount?.toLocaleString()}</span>
                </div>
                <div className="receipt-detail-row"><span>Method</span><span>{r.paymentMethod}</span></div>
                {r.feesIncluded?.length > 0 && (
                  <div className="receipt-detail-row" style={{ flexDirection:"column", gap:"4px" }}>
                    <span>Fees Included</span>
                    <span style={{ color:"#64748b" }}>{r.feesIncluded.join(", ")}</span>
                  </div>
                )}
                <div className="receipt-actions">
                  <button onClick={() => handleDownload(r)} disabled={generating === r.receiptId} style={{ opacity: generating === r.receiptId ? 0.6 : 1 }}>
                    <i className={`bx ${generating === r.receiptId ? "bx-loader-alt bx-spin" : "bxs-download"}`} style={{ marginRight:"4px" }}></i>
                    {generating === r.receiptId ? "Generating..." : "Download PDF"}
                  </button>
                  <button onClick={() => handlePrint(r)}>
                    <i className="bx bxs-printer" style={{ marginRight:"4px" }}></i>Print
                  </button>
                </div>
              </div>
            ))}
          </div>
        </>
      )}
    </>
  );
};

export default ReceiptsPage;
